# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

def require_pods
    pod 'IQKeyboardManager', '~> 5.0.7'
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'Masonry', '~> 1.1.0'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'MJRefresh', '~> 3.1.15.3'
    pod 'YTKNetwork', '~> 2.0.4'
    pod 'MJExtension', '~> 3.0.13'
    pod 'CocoaSecurity', '~> 1.2.4'
    pod 'DateTools', '~> 2.0.0'
    pod 'DZNEmptyDataSet', :podspec => 'https://raw.githubusercontent.com/y1024/DZNEmptyDataSet/1.8.2/DZNEmptyDataSet.podspec'
    pod 'SDWebImage', '~> 3.7.5'
    pod 'DeviceUtil'
    
end


target 'template' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  require_pods
  


end
